---
driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  data_bags_path: test/data_bags
  environments_path: test/environments
  client_rb:
    environment: dev

verifier:
  name: inspec
  attrs:
    - test/attributes/dev.yml

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - 'recipe[tor::default]'
    attributes:
      tor:
        backup_ip: '127.0.0.1'
